### PR TITLE
Correct variable name in fmquestion loader

### PR DESCRIPTION
**Pull request by reinbach**
[ch24602]

### CODE REVIEW

**Review by domdinicola — APPROVED** [review]

**Comment by domdinicola** [comment]
shall we add a test?

**Comment by reinbach** [comment]
> shall we add a test?

Tests would be great, there is a bunch of work that needs to be done around this, to make it simple to add tests around loaders. Still trying to wrap my head around how the current tests actually work.

**Comment by domdinicola** [comment]
> > shall we add a test?
> 
> Tests would be great, there is a bunch of work that needs to be done around this, to make it simple to add tests around loaders. Still trying to wrap my head around how the current tests actually work.

Maybe we can ask @saxix

**Comment by reinbach** [comment]
> > > shall we add a test?
> > 
> > 
> > Tests would be great, there is a bunch of work that needs to be done around this, to make it simple to add tests around loaders. Still trying to wrap my head around how the current tests actually work.
> 
> Maybe we can ask @saxix

We can, there are a ton of tests that automatically hit each of the loaders, etc. It's just that in some of these that we miss some of the nuances of the logic in place

**Pull request merged**
